REST Client
### CREATE - criar um aluno ( POST )
POST http :// localhost :3000/ alunos
Content - Type : application / json
{
" id ": 1 ,
" nome ": " Ana " ,
" nota ": 8.5
}
### READ - listar todos os alunos ( GET )
GET http :// localhost :3000/ alunos
### READ - buscar um aluno especifico ( GET )
GET http :// localhost :3000/ alunos /1
### UPDATE - atualizar um aluno ( PUT )
PUT http :// localhost :3000/ alunos /1
Content - Type : application / json
{
" nome ": " Ana Paula " ,
" nota ": 9.0
}
### DELETE - apagar um aluno ( DELETE )
DELETE http :// localhost :3000/ alunos /1
# CREATE - criar um aluno ( POST )
curl -X POST http :// localhost :3000/ alunos \
-H " Content - Type : application / json " \
-d ’{" id ": 1 , " nome ": "Ana" , " nota ": 8.5} ’
# READ - listar todos os alunos (GET )
curl http :// localhost :3000/ alunos
# READ - buscar um aluno especifico (GET)
curl http :// localhost :3000/ alunos /1
# UPDATE - atualizar um aluno (PUT)
curl -X PUT http :// localhost :3000/ alunos /1 \
-H " Content - Type : application / json " \
-d ’{" nome ": "Ana Paula " , " nota ": 9.0} ’
# DELETE - apagar um aluno ( DELETE )
curl -X DELETE http :// localhost :3000/ alunos /1
curl -i http :// localhost :3000/ alunos